const { defineConfig } = require('cz-git')

const SCOPES = [
    { name: 'frontend', description: 'Vue 前端' },
    { name: 'backend', description: 'Spring Boot 后端' },
    { name: 'docs', description: '文档' },
    { name: 'deploy', description: '部署配置' },
    { name: 'repo', description: '仓库工具链（husky/commitlint 等）' },
]

const SCOPE_NAMES = SCOPES.map(({ name }) => name)

module.exports = defineConfig({
    extends: ['@commitlint/config-conventional'],
    rules: {
        'scope-enum': [2, 'always', SCOPE_NAMES],
        'scope-empty': [2, 'never'],
    },
    prompt: {
        alias: { fd: 'docs: 修正错别字' },
        messages: {
            type: '请选择提交类型：',
            scope: '请选择影响范围：',
            customScope: '请输入自定义影响范围：',
            subject: '请简要描述本次变更：\n',
            body: '请输入详细描述（可选，用 "|" 换行）：\n',
            breaking: '请列出破坏性变更（可选，用 "|" 换行）：\n',
            footerPrefixesSelect: '请选择关联 Issue 类型（可选）：',
            customFooterPrefix: '请输入 Issue 前缀：',
            footer: '请填写关联 Issue，如 #31、#34：\n',
            generatingByAI: '正在生成 AI 提交描述...',
            generatedSelectByAI: '请选择 AI 生成的描述：',
            confirmCommit: '确认使用以上信息提交？',
        },
        types: [
            { value: 'feat', name: 'feat:     ✨  新功能', emoji: ':sparkles:' },
            { value: 'fix', name: 'fix:      🐛  修复缺陷', emoji: ':bug:' },
            { value: 'docs', name: 'docs:     📝  文档变更', emoji: ':memo:' },
            { value: 'style', name: 'style:    💄  代码格式（不影响逻辑）', emoji: ':lipstick:' },
            { value: 'refactor', name: 'refactor: ♻️   重构（非修复也非新功能）', emoji: ':recycle:' },
            { value: 'perf', name: 'perf:     ⚡️  性能优化', emoji: ':zap:' },
            { value: 'test', name: 'test:     ✅  测试相关', emoji: ':white_check_mark:' },
            { value: 'build', name: 'build:    📦️   构建系统或依赖变更', emoji: ':package:' },
            { value: 'ci', name: 'ci:       🎡  CI 配置或脚本变更', emoji: ':ferris_wheel:' },
            { value: 'chore', name: 'chore:    🔨  其他杂项（不改动 src 或 test）', emoji: ':hammer:' },
            { value: 'revert', name: 'revert:   ⏪️  回滚提交', emoji: ':rewind:' },
        ],
        useEmoji: true,
        emojiAlign: 'center',
        useAI: false,
        aiNumber: 1,
        themeColorCode: '',
        scopes: SCOPES,
        allowCustomScopes: false,
        allowEmptyScopes: false,
        customScopesAlign: 'bottom',
        customScopesAlias: '自定义',
        emptyScopesAlias: '跳过',
        upperCaseSubject: null,
        markBreakingChangeMode: false,
        allowBreakingChanges: ['feat', 'fix'],
        breaklineNumber: 100,
        breaklineChar: '|',
        skipQuestions: [],
        issuePrefixes: [{ value: 'closed', name: 'closed:   已处理的 Issue' }],
        customIssuePrefixAlign: 'top',
        emptyIssuePrefixAlias: '跳过',
        customIssuePrefixAlias: '自定义',
        allowCustomIssuePrefix: true,
        allowEmptyIssuePrefix: true,
        confirmColorize: true,
        scopeOverrides: {
            feat: [{ name: 'frontend' }, { name: 'backend' }],
            fix: [{ name: 'frontend' }, { name: 'backend' }],
            docs: [{ name: 'docs' }, { name: 'frontend' }, { name: 'backend' }],
            ci: [{ name: 'deploy' }, { name: 'repo' }],
            build: [{ name: 'frontend' }, { name: 'backend' }, { name: 'repo' }],
            chore: [{ name: 'frontend' }, { name: 'backend' }, { name: 'repo' }, { name: 'deploy' }],
        },
        defaultBody: '',
        defaultIssues: '',
        defaultScope: '',
        defaultSubject: '',
    },
})
